services:
  nginx:
    build:
      context: requirements/nginx
      args:
          DOMAIN: ${DOMAIN}
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "443:443"
    volumes:
        - wp-vol:/var/www/html
    networks:
        - inception_net
    env_file:
        - .env

  mariadb:
    build:
      context: requirements/mariadb
      args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    expose:
        - "3306"
    volumes:
        - mdb-vol:/var/lib/mysql
    networks:
        - inception_net
    env_file:
        - .env

  wordpress:
    build:
      context: requirements/wordpress
      args:
          WP_PASSWORD: ${WP_PASSWORD}
          WP_ADMIN: ${WP_ADMIN}
          WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
          NEW_USER_PASS: ${NEW_USER_PASS}
          DOMAIN: ${DOMAIN}
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    expose:
        - "9000"
    depends_on:
        - mariadb
    volumes:
        - wp-vol:/var/www/html
    networks:
        - inception_net
    env_file:
        - .env

volumes:
    mdb-vol:
        name: mdb-vol
        driver: local
        driver_opts:
            type: none
            device: /home/mfirdous/data/mdb
            o: bind
    wp-vol:
        name: wp-vol
        driver: local
        driver_opts:
            type: none
            device: /home/mfirdous/data/wp
            o: bind

networks:
   inception_net:
       driver: bridge
