services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
        - "80:80"
      # - "443:443"
    volumes:
        - /home/mfirdous/data/wp-vol:/var/www/html
    networks:
        - inception_net
    env_file:
        - .env

  mariadb:
    build:
      context: requirements/mariadb
      args:
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    expose:
        - "3306"
    volumes:
        - mdb-vol:/var/lib/mysql
    networks:
        - inception_net
    env_file:
        - .env

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    # image: wordpress:4.7.1-php7.0-fpm
    container_name: wordpress
    restart: unless-stopped
    ports:
        - "9000:9000"
    depends_on:
        - mariadb
    volumes:
        - wp-vol:/var/www/html
    # environment:
    #   WORDPRESS_DB_NAME: wpdb
    #   WORDPRESS_DB_HOST: mariadb:3306
    #   WORDPRESS_DB_USER: mfirdous
    #   WORDPRESS_DB_PASSWORD: 123
    networks:
        - inception_net
    env_file:
        - .env

volumes:
    mdb-vol:
        name: mdb-vol
        driver: local
        driver_opts:
            type: none
            device: /home/mfirdous/data/mdb
            o: bind
    wp-vol:
        name: wp-vol
        driver: local
        driver_opts:
            type: none
            device: /home/mfirdous/data/wp
            o: bind

networks:
   inception_net:
       driver: bridge
